# Generated by Django 4.1.3 on 2022-11-30 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_value', models.CharField(max_length=10000)),
                ('msg_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('msg_user', models.CharField(max_length=100)),
                ('msg_room', models.CharField(max_length=50)),
            ],
        ),
    ]
